### ISSUE TITLE
After closing address bar, reclicking parcel should display address again

### ISSUE THREAD

**Issue by juancatothe** [CityOfDetroit/canvas#48] opened 2019-07-23 16:31 UTC

**Comment by mikefresh** [comment] 2019-08-01 17:28
I think this might be solved now? Im unable to recreate.

**Comment by juancatothe** [comment] 2019-08-05 18:38
@mikefresh I've been looking into this, but could use your help.

Steps to recreate: 
-Click a building
-Swipe the address down
-Click any building, nothing will show up

**Comment by mikefresh** [comment] 2019-08-09 14:13
Duplicate of #60

**Closed by mikefresh** 2019-08-09 14:13 UTC
